name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Update version number
        run: |
          VERSION_NUMBER=$(date +'%Y%m%d')-${{github.run_number}}-${{github.run_attempt}}"
          echo "Setting version to $VERSION_NUMBER"
          sed -i "s/^version=.*/version=$VERSION_NUMBER/" gradle.properties
      - name: Build and publish package
        run: ./gradlew build publish
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
